# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[default.extend-words]
trivias = "trivias"
trivia = "trivia"
inferrable = "inferrable"

[files]
extend-exclude = ["src/docs/guide/usage/linter/rules", "pnpm-lock.yaml"]
